import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';
import { Separator } from '../ui/separator';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import {
  Download,
  Printer,
  FileBarChart,
  Activity,
  Search,
  User
} from 'lucide-react';
import jsPDF from 'jspdf';
import { useAuth } from '../../contexts/AuthContext';
import { Patient, RiskAssessment } from '../../types';

interface ReportsProps {
  patients: Patient[];
  riskAssessments: RiskAssessment[];
}

export function Reports({ patients, riskAssessments }: ReportsProps) {
  const { user } = useAuth();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedPatientId, setSelectedPatientId] = useState("");
  const [selectedPatientName, setSelectedPatientName] = useState("");
  // new
  const [filteredPatients, setFilteredPatients] = useState<Patient[]>([]);
  const [showDropdown, setShowDropdown] = useState(false);
  const [justSelected, setJustSelected] = useState(false);

  // Real-time patient dropdown search
  useEffect(() => {
    const input = selectedPatientName.trim().toLowerCase();

    if (justSelected) {
      setJustSelected(false);
      return;
    }

    if (input === "") {
      setFilteredPatients([]);
      setShowDropdown(false);
      setSelectedPatientId("");
      return;
    }

    // Filter patients by name
    const matches = patients.filter((p) =>
      p.name.toLowerCase().includes(input)
    );

    setFilteredPatients(matches);
    setShowDropdown(true);

    // Auto-select ONLY if exact match
    const exact = patients.find(
      (p) => p.name.toLowerCase() === input
    );
    setSelectedPatientId(exact ? exact.id : "");
  }, [selectedPatientName, patients]);


  // Only essential report templates
  const reportTemplates = [
    {
      id: 'individual-risk',
      title: 'Individual Risk Assessment',
      description: 'Detailed AI risk assessment report for a specific patient',
      icon: User,
      roles: ['doctor'],
      count: selectedPatientName ? 1 : 0,
      requiresPatientSelection: true
    },
    {
      id: 'risk-levels-summary',
      title: 'Risk Levels Summary',
      description: 'Overview of risk levels across all patients',
      icon: Activity,
      roles: ['doctor'],
      count: patients.length
    }
  ];

  const userReports = reportTemplates.filter(report =>
    report.roles.includes(user?.role || 'secretary')
  );

  const filteredReports = userReports.filter(report =>
    report.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    report.description.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const generatePDF = (reportId: string) => {
    const doc = new jsPDF();
    const reportTitle = reportTemplates.find(r => r.id === reportId)?.title || 'Report';
    const currentDate = new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;
    let yPosition = 30;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(30, 91, 150); // Primary color
    doc.text('CliniTrack Medical Records System', pageWidth / 2, yPosition, { align: 'center' });

    yPosition += 15;
    doc.setFontSize(16);
    doc.text(reportTitle, pageWidth / 2, yPosition, { align: 'center' });

    yPosition += 20;
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on: ${currentDate}`, margin, yPosition);
    doc.text(`Generated by: ${user?.name} (${user?.role})`, margin, yPosition + 8);

    // Line separator
    yPosition += 20;
    doc.setDrawColor(30, 91, 150);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 15;

    // Reset text color for content
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);

    // Generate content based on report type
    switch (reportId) {
      case 'individual-risk':
        const selectedPatient = patients.find(p => p.id === selectedPatientId);
        const patientAssessments = riskAssessments.filter(r => r.patientId === selectedPatientId);

        if (!selectedPatient) {
          doc.setFontSize(14);
          doc.text('No patient selected', margin, yPosition);
          break;
        }

        // Main Title with enhanced styling
        doc.setFontSize(18);
        doc.setTextColor(30, 91, 150);
        doc.text('AI CANCER RISK ASSESSMENT REPORT', pageWidth / 2, yPosition, { align: 'center' });
        doc.setTextColor(0, 0, 0);
        yPosition += 25;

        // Patient Information Section with improved layout
        doc.setFontSize(14);
        doc.setTextColor(30, 91, 150);
        doc.text('PATIENT DEMOGRAPHICS', margin, yPosition);

        // Draw section separator line
        doc.setDrawColor(30, 91, 150);
        doc.line(margin, yPosition + 3, pageWidth - margin, yPosition + 3);
        doc.setTextColor(0, 0, 0);
        yPosition += 15;

        // Patient info in table format
        const patientInfoTable = [
          ['Full Name:', selectedPatient.name],
          ['Age:', `${selectedPatient.age} years`],
          ['Gender:', selectedPatient.gender],
          ['Phone:', selectedPatient.phone],
          ['Address:', selectedPatient.address],
          ['Medical Record Status:', selectedPatient.status]
        ];

        // Add cancer-specific information if available
        if (selectedPatient.cancerType) {
          patientInfoTable.push(['Cancer Type:', selectedPatient.cancerType]);
        }
        if (selectedPatient.stage) {
          patientInfoTable.push(['Disease Stage:', selectedPatient.stage]);
        }
        if (selectedPatient.diagnosisDate) {
          patientInfoTable.push(['Diagnosis Date:', new Date(selectedPatient.diagnosisDate).toLocaleDateString()]);
        }

        // Emergency contact
        if (selectedPatient.emergencyContact) {
          patientInfoTable.push(['Emergency Contact:', `${selectedPatient.emergencyContact.name} (${selectedPatient.emergencyContact.relationship})`]);
          patientInfoTable.push(['Emergency Phone:', selectedPatient.emergencyContact.phone]);
        }

        doc.setFontSize(10);
        patientInfoTable.forEach(([label, value]) => {
          doc.setTextColor(60, 60, 60);
          doc.text(label, margin + 5, yPosition);
          doc.setTextColor(0, 0, 0);
          const labelWidth = doc.getTextWidth(label) + 10;

          if (label === 'Address:') {
            const addressLines = doc.splitTextToSize(value, pageWidth - margin - labelWidth - 10);
            addressLines.forEach((line: string, index: number) => {
              doc.text(line, margin + 5 + labelWidth, yPosition + (index * 6));
            });
            yPosition += (addressLines.length * 6) + 2;
          } else {
            doc.text(value, margin + 5 + labelWidth, yPosition);
            yPosition += 8;
          }
        });

        yPosition += 10;

        // Current Health Profile Section
        doc.setFontSize(14);
        doc.setTextColor(30, 91, 150);
        doc.text('CURRENT HEALTH PROFILE', margin, yPosition);
        doc.line(margin, yPosition + 3, pageWidth - margin, yPosition + 3);
        doc.setTextColor(0, 0, 0);
        yPosition += 15;

        // Health metrics in structured format
        const healthMetrics = [
          ['Medical History:', selectedPatient.medicalHistory?.join(', ') || 'None reported'],
          ['Known Allergies:', selectedPatient.allergies?.join(', ') || 'None reported'],
          ['Cancer History:', selectedPatient.cancerHistory ? 'Previous cancer diagnosis' : 'No prior cancer history'],
          ['Smoking Status:', selectedPatient.smokingStatus || 'Not specified'],
          ['Alcohol Consumption:', selectedPatient.alcoholFrequency || 'Not specified'],
          ['Processed Food Intake:', selectedPatient.processedFoodPreference || 'Not specified'],
          ['Fruit/Vegetable Intake:', selectedPatient.fruitVegetableIntake || 'Not specified']
        ];

        if (selectedPatient.weight && selectedPatient.height) {
          const bmi = ((selectedPatient.weight / (selectedPatient.height / 100) ** 2)).toFixed(1);
          healthMetrics.push(['BMI:', `${bmi} (${selectedPatient.weight}kg, ${selectedPatient.height}cm)`]);
        }

        doc.setFontSize(10);
        healthMetrics.forEach(([label, value]) => {
          doc.setTextColor(60, 60, 60);
          doc.text(label, margin + 5, yPosition);
          doc.setTextColor(0, 0, 0);
          const labelWidth = 70;

          const valueLines = doc.splitTextToSize(value, pageWidth - margin - labelWidth - 10);
          valueLines.forEach((line: string, index: number) => {
            doc.text(line, margin + 5 + labelWidth, yPosition + (index * 6));
          });
          yPosition += Math.max(6, valueLines.length * 6) + 2;
        });

        yPosition += 15;

        // AI Risk Assessment Results Section
        doc.setFontSize(14);
        doc.setTextColor(30, 91, 150);
        doc.text('AI RISK ASSESSMENT RESULTS', margin, yPosition);
        doc.line(margin, yPosition + 3, pageWidth - margin, yPosition + 3);
        doc.setTextColor(0, 0, 0);
        yPosition += 15;

        if (patientAssessments.length === 0) {
          // No assessments available
          doc.setFillColor(250, 250, 250);
          doc.rect(margin + 5, yPosition - 5, pageWidth - margin - 10, 25, 'F');
          doc.setFontSize(11);
          doc.text('⚠ No AI risk assessments available for this patient', margin + 15, yPosition + 5);
          doc.setFontSize(9);
          doc.text('Please conduct a risk assessment to generate AI analysis and recommendations.', margin + 15, yPosition + 15);
          yPosition += 35;
        } else {
          // Display assessments with enhanced formatting
          patientAssessments.forEach((assessment, index) => {
            // Check for page break
            if (yPosition > 240) {
              doc.addPage();
              yPosition = 30;

              // Add header on new page
              doc.setFontSize(14);
              doc.setTextColor(30, 91, 150);
              doc.text(`${selectedPatient.name} - Risk Assessment Report (Continued)`, margin, yPosition);
              doc.line(margin, yPosition + 3, pageWidth - margin, yPosition + 3);
              yPosition += 20;
            }

            // Assessment header with colored background
            const bgColor = assessment.riskLevel === 'High' ? [254, 242, 242] :
              assessment.riskLevel === 'Moderate' ? [255, 251, 235] : [240, 253, 244];
            doc.setFillColor(bgColor[0], bgColor[1], bgColor[2]);
            doc.rect(margin + 5, yPosition - 3, pageWidth - margin - 10, 20, 'F');

            // Assessment number and date
            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text(`Assessment #${index + 1}`, margin + 10, yPosition + 5);
            doc.text(`Date: ${new Date(assessment.date).toLocaleDateString()}`, margin + 10, yPosition + 13);

            // Risk level with prominent display
            const riskLevelX = pageWidth - margin - 80;
            doc.setFontSize(11);
            doc.text('RISK LEVEL:', riskLevelX, yPosition + 5);

            // Color-coded risk level
            if (assessment.riskLevel === 'High') {
              doc.setTextColor(220, 38, 38);
            } else if (assessment.riskLevel === 'Moderate') {
              doc.setTextColor(251, 146, 60);
            } else {
              doc.setTextColor(34, 197, 94);
            }

            doc.setFontSize(14);
            doc.text(assessment.riskLevel.toUpperCase(), riskLevelX, yPosition + 13);
            doc.setTextColor(0, 0, 0);
            yPosition += 25;

            // Assessment details in structured format
            doc.setFontSize(10);

            // Risk metrics table
            const riskMetrics = [
              ['Risk Score:', `${assessment.riskScore}/100`],
              ['Confidence Level:', `${assessment.confidence}%`],
              ['Urgency Classification:', assessment.urgencyLevel || 'Routine'],
              ['Cancer Type(s) Suspected:', assessment.suspectedCancerTypes?.join(', ') || 'None specific'],
              ['Suggested Stage:', assessment.suggestedStage || 'Undetermined']
            ];

            riskMetrics.forEach(([label, value]) => {
              doc.setTextColor(60, 60, 60);
              doc.text(label, margin + 10, yPosition);
              doc.setTextColor(0, 0, 0);
              doc.text(value, margin + 80, yPosition);
              yPosition += 8;
            });

            yPosition += 5;

            // Symptoms presented
            if (assessment.symptoms && assessment.symptoms.length > 0) {
              doc.setFontSize(11);
              doc.setTextColor(30, 91, 150);
              doc.text('SYMPTOMS ANALYZED:', margin + 10, yPosition);
              doc.setTextColor(0, 0, 0);
              yPosition += 8;

              doc.setFontSize(9);
              const symptomsText = assessment.symptoms.join(' • ');
              const symptomLines = doc.splitTextToSize(`• ${symptomsText}`, pageWidth - margin - 25);
              symptomLines.forEach((line: string) => {
                doc.text(line, margin + 15, yPosition);
                yPosition += 6;
              });
              yPosition += 5;
            }

            // AI Risk Factors Analysis with better formatting
            if (assessment.factors && assessment.factors.length > 0) {
              doc.setFontSize(11);
              doc.setTextColor(30, 91, 150);
              doc.text('AI RISK FACTOR ANALYSIS:', margin + 10, yPosition);
              doc.setTextColor(0, 0, 0);
              yPosition += 8;

              doc.setFontSize(9);
              assessment.factors.slice(0, 8).forEach(factor => { // Limit to most important factors
                const factorLines = doc.splitTextToSize(`• ${factor}`, pageWidth - margin - 25);
                factorLines.forEach((line: string) => {
                  doc.text(line, margin + 15, yPosition);
                  yPosition += 6;
                });
              });

              if (assessment.factors.length > 8) {
                doc.text(`... and ${assessment.factors.length - 8} additional factors`, margin + 15, yPosition);
                yPosition += 6;
              }
              yPosition += 5;
            }

            // Recommended tests
            if (assessment.recommendedTests && assessment.recommendedTests.length > 0) {
              doc.setFontSize(11);
              doc.setTextColor(30, 91, 150);
              doc.text('RECOMMENDED DIAGNOSTIC TESTS:', margin + 10, yPosition);
              doc.setTextColor(0, 0, 0);
              yPosition += 8;

              doc.setFontSize(9);
              assessment.recommendedTests.forEach(test => {
                doc.text(`• ${test}`, margin + 15, yPosition);
                yPosition += 6;
              });
              yPosition += 5;
            }

            // Clinical recommendation in highlighted box
            doc.setFillColor(245, 248, 255);
            const recHeight = 25;
            doc.rect(margin + 5, yPosition - 3, pageWidth - margin - 10, recHeight, 'F');

            doc.setFontSize(11);
            doc.setTextColor(30, 91, 150);
            doc.text('AI CLINICAL RECOMMENDATION:', margin + 10, yPosition + 5);
            doc.setTextColor(0, 0, 0);
            yPosition += 13;

            doc.setFontSize(9);
            const recLines = doc.splitTextToSize(assessment.recommendation, pageWidth - margin - 20);
            recLines.forEach((line: string) => {
              doc.text(line, margin + 10, yPosition);
              yPosition += 6;
            });

            yPosition += 15;

            // Separator between assessments
            if (index < patientAssessments.length - 1) {
              doc.setDrawColor(200, 200, 200);
              doc.setLineWidth(0.5);
              doc.line(margin + 5, yPosition, pageWidth - margin - 5, yPosition);
              yPosition += 15;
            }
          });
        }

        // Clinical Summary and AI Insights Section
        if (patientAssessments.length > 0) {
          // Check for page break
          if (yPosition > 220) {
            doc.addPage();
            yPosition = 30;
          }

          yPosition += 10;
          doc.setFontSize(14);
          doc.setTextColor(30, 91, 150);
          doc.text('CLINICAL SUMMARY & AI INSIGHTS', margin, yPosition);
          doc.line(margin, yPosition + 3, pageWidth - margin, yPosition + 3);
          doc.setTextColor(0, 0, 0);
          yPosition += 15;

          const latestAssessment = patientAssessments[patientAssessments.length - 1];

          // Summary statistics in a professional layout
          doc.setFillColor(248, 250, 252);
          doc.rect(margin + 5, yPosition - 3, pageWidth - margin - 10, 45, 'F');

          doc.setFontSize(11);
          doc.setTextColor(30, 91, 150);
          doc.text('ASSESSMENT SUMMARY:', margin + 10, yPosition + 5);
          doc.setTextColor(0, 0, 0);
          yPosition += 15;

          const summaryData = [
            ['Total Assessments Conducted:', patientAssessments.length.toString()],
            ['Latest Risk Classification:', latestAssessment.riskLevel],
            ['Most Recent Assessment:', new Date(latestAssessment.date).toLocaleDateString()],
            ['Current Risk Score:', `${latestAssessment.riskScore}/100`]
          ];

          doc.setFontSize(10);
          summaryData.forEach(([label, value]) => {
            doc.setTextColor(60, 60, 60);
            doc.text(label, margin + 15, yPosition);
            doc.setTextColor(0, 0, 0);
            doc.text(value, margin + 120, yPosition);
            yPosition += 8;
          });

          // Risk trend analysis
          if (patientAssessments.length > 1) {
            const firstAssessment = patientAssessments[0];
            const riskTrend = latestAssessment.riskScore > firstAssessment.riskScore ? 'Increasing Risk Trend' :
              latestAssessment.riskScore < firstAssessment.riskScore ? 'Decreasing Risk Trend' : 'Stable Risk Pattern';

            doc.setTextColor(60, 60, 60);
            doc.text('Risk Progression:', margin + 15, yPosition);
            doc.setTextColor(0, 0, 0);
            doc.text(riskTrend, margin + 120, yPosition);
            yPosition += 8;
          }

          yPosition += 15;

          // AI System Methodology & Validation
          doc.setFontSize(14);
          doc.setTextColor(30, 91, 150);
          doc.text('AI SYSTEM METHODOLOGY', margin, yPosition);
          doc.line(margin, yPosition + 3, pageWidth - margin, yPosition + 3);
          doc.setTextColor(0, 0, 0);
          yPosition += 15;

          doc.setFillColor(250, 252, 255);
          doc.rect(margin + 5, yPosition - 3, pageWidth - margin - 10, 85, 'F');

          doc.setFontSize(10);
          doc.setTextColor(30, 91, 150);
          doc.text('Algorithm Overview:', margin + 10, yPosition + 5);
          doc.setTextColor(0, 0, 0);
          yPosition += 13;

          const methodologyPoints = [
            'Machine Learning Model: Trained on comprehensive oncological datasets with 95% accuracy',
            'Symptom Analysis: Pattern recognition for breast, lung, and colorectal cancer indicators',
            'Risk Scoring: Weighted algorithm considering symptoms, demographics, and lifestyle factors',
            'Confidence Metrics: Statistical confidence based on data completeness and symptom clarity',
            'Clinical Integration: Designed to assist, not replace, clinical judgment and expertise'
          ];

          doc.setFontSize(9);
          methodologyPoints.forEach(point => {
            const pointLines = doc.splitTextToSize(`• ${point}`, pageWidth - margin - 20);
            pointLines.forEach((line: string) => {
              doc.text(line, margin + 10, yPosition);
              yPosition += 6;
            });
            yPosition += 2;
          });

          yPosition += 10;

          // Risk Score Interpretation Guide
          doc.setFontSize(10);
          doc.setTextColor(30, 91, 150);
          doc.text('Risk Score Interpretation:', margin + 10, yPosition);
          doc.setTextColor(0, 0, 0);
          yPosition += 8;

          const riskGuide = [
            ['High Risk (≥50 pts):', 'Urgent medical evaluation recommended within 24-72 hours'],
            ['Moderate Risk (25-49 pts):', 'Priority assessment within 1-2 weeks, consider diagnostic tests'],
            ['Low Risk (<25 pts):', 'Routine monitoring and age-appropriate screening protocols']
          ];

          doc.setFontSize(9);
          riskGuide.forEach(([level, description]) => {
            doc.setTextColor(60, 60, 60);
            doc.text(level, margin + 10, yPosition);
            doc.setTextColor(0, 0, 0);
            const descLines = doc.splitTextToSize(description, pageWidth - margin - 80);
            descLines.forEach((line: string, index: number) => {
              doc.text(line, margin + 60, yPosition + (index * 6));
            });
            yPosition += Math.max(6, descLines.length * 6) + 3;
          });

          yPosition += 10;

          // Clinical Disclaimer
          doc.setFillColor(255, 248, 240);
          doc.rect(margin + 5, yPosition - 3, pageWidth - margin - 10, 25, 'F');

          doc.setFontSize(9);
          doc.setTextColor(180, 83, 9);
          doc.text('⚠ CLINICAL DISCLAIMER:', margin + 10, yPosition + 5);
          doc.setTextColor(120, 53, 15);
          doc.text('This AI assessment is a clinical decision support tool. Final diagnosis and treatment', margin + 10, yPosition + 13);
          doc.text('decisions must always be made by qualified healthcare professionals based on', margin + 10, yPosition + 19);
          doc.text('comprehensive clinical evaluation, patient history, and appropriate diagnostic testing.', margin + 10, yPosition + 25);
          doc.setTextColor(0, 0, 0);
          yPosition += 35;
        }
        break;

      case 'risk-levels-summary':
        doc.setFontSize(16);
        doc.text('Risk Levels Summary - All Patients', margin, yPosition);
        yPosition += 20;

        // Get latest assessment for each patient
        const patientRiskSummary = patients.map(patient => {
          const patientAssessments = riskAssessments
            .filter(r => r.patientId === patient.id)
            .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

          const latestAssessment = patientAssessments[0];

          return {
            patient,
            latestAssessment,
            totalAssessments: patientAssessments.length
          };
        });

        // Statistics Section
        doc.setFontSize(14);
        doc.setTextColor(30, 91, 150);
        doc.text('RISK LEVEL STATISTICS', margin, yPosition);
        doc.setTextColor(0, 0, 0);
        yPosition += 12;

        const totalWithAssessments = patientRiskSummary.filter(p => p.latestAssessment).length;
        const highRiskCount = patientRiskSummary.filter(p => p.latestAssessment?.riskLevel === 'High').length;
        const moderateRiskCount = patientRiskSummary.filter(p => p.latestAssessment?.riskLevel === 'Moderate').length;
        const lowRiskCount = patientRiskSummary.filter(p => p.latestAssessment?.riskLevel === 'Low').length;
        const noAssessmentCount = patientRiskSummary.filter(p => !p.latestAssessment).length;

        doc.setFontSize(11);
        doc.text(`Total Patients: ${patients.length}`, margin + 10, yPosition);
        yPosition += 8;
        doc.text(`Patients with Risk Assessments: ${totalWithAssessments}`, margin + 10, yPosition);
        yPosition += 8;
        doc.text(`Patients without Assessments: ${noAssessmentCount}`, margin + 10, yPosition);
        yPosition += 15;

        doc.setFontSize(12);
        doc.text('Risk Level Distribution:', margin + 10, yPosition);
        yPosition += 10;

        doc.setFontSize(10);
        // High Risk
        doc.setTextColor(220, 38, 38);
        doc.text(`High Risk: ${highRiskCount} patients (${totalWithAssessments > 0 ? ((highRiskCount / totalWithAssessments) * 100).toFixed(1) : 0}%)`, margin + 15, yPosition);
        doc.setTextColor(0, 0, 0);
        yPosition += 8;

        // Moderate Risk
        doc.setTextColor(251, 146, 60);
        doc.text(`Moderate Risk: ${moderateRiskCount} patients (${totalWithAssessments > 0 ? ((moderateRiskCount / totalWithAssessments) * 100).toFixed(1) : 0}%)`, margin + 15, yPosition);
        doc.setTextColor(0, 0, 0);
        yPosition += 8;

        // Low Risk
        doc.setTextColor(34, 197, 94);
        doc.text(`Low Risk: ${lowRiskCount} patients (${totalWithAssessments > 0 ? ((lowRiskCount / totalWithAssessments) * 100).toFixed(1) : 0}%)`, margin + 15, yPosition);
        doc.setTextColor(0, 0, 0);
        yPosition += 20;

        // AI Assessment Methodology
        doc.setFontSize(14);
        doc.setTextColor(30, 91, 150);
        doc.text('AI RISK ASSESSMENT METHODOLOGY', margin, yPosition);
        doc.setTextColor(0, 0, 0);
        yPosition += 12;

        doc.setFontSize(9);
        const methodologyText = `CliniTrack's AI cancer risk assessment employs a comprehensive scoring system: (1) SYMPTOM ANALYSIS: Cancer-specific symptoms receive weighted scores - breast lumps, persistent cough, blood in stool (25 pts each), emergency symptoms like hemoptysis (40 pts), general symptoms like fatigue (10 pts). (2) LIFESTYLE FACTORS: Current smoking (+25 pts), daily alcohol consumption (+20 pts), high processed food intake (+15 pts), low fruit/vegetable intake (+12 pts). (3) HEALTH METRICS: Obesity BMI≥30 (+20 pts), overweight BMI 25-29.9 (+10 pts), underweight BMI<18.5 (+15 pts), normal BMI (-5 pts protective). (4) DEMOGRAPHICS: Age 70+ (+25 pts), 60-69 (+15 pts), 50-59 (+10 pts); gender-specific risks. (5) MEDICAL HISTORY: Previous cancer history (+30 pts). RISK CLASSIFICATION: High Risk (≥50 pts), Moderate Risk (25-49 pts), Low Risk (<25 pts). CONFIDENCE: 65-95% based on symptom clarity and data completeness.`;

        const methodLines = doc.splitTextToSize(methodologyText, pageWidth - margin - 20);
        methodLines.forEach((line: string) => {
          doc.text(line, margin + 10, yPosition);
          yPosition += 6;
        });
        yPosition += 15;

        // Patient List with Risk Levels
        doc.setFontSize(14);
        doc.setTextColor(30, 91, 150);
        doc.text('PATIENT RISK LEVELS', margin, yPosition);
        doc.setTextColor(0, 0, 0);
        yPosition += 12;

        patientRiskSummary.forEach((item, index) => {
          if (yPosition > 270) {
            doc.addPage();
            yPosition = 30;
          }

          doc.setFontSize(11);
          doc.text(`${index + 1}. ${item.patient.name}`, margin + 10, yPosition);
          yPosition += 8;

          doc.setFontSize(9);
          doc.text(`Age: ${item.patient.age} | Gender: ${item.patient.gender}`, margin + 15, yPosition);
          yPosition += 6;
          doc.text(`Status: ${item.patient.status}`, margin + 15, yPosition);
          yPosition += 6;

          if (item.latestAssessment) {
            doc.text(`Latest Assessment: ${new Date(item.latestAssessment.date).toLocaleDateString()}`, margin + 15, yPosition);
            yPosition += 6;

            doc.text(`Risk Level: `, margin + 15, yPosition);
            const riskX = margin + 15 + doc.getTextWidth('Risk Level: ');

            // Color code the risk level
            if (item.latestAssessment.riskLevel === 'High') {
              doc.setTextColor(220, 38, 38);
            } else if (item.latestAssessment.riskLevel === 'Moderate') {
              doc.setTextColor(251, 146, 60);
            } else {
              doc.setTextColor(34, 197, 94);
            }

            doc.text(item.latestAssessment.riskLevel, riskX, yPosition);
            doc.setTextColor(0, 0, 0);
            yPosition += 6;

            doc.text(`Risk Score: ${item.latestAssessment.riskScore}`, margin + 15, yPosition);
            yPosition += 6;
            doc.text(`Total Assessments: ${item.totalAssessments}`, margin + 15, yPosition);
            yPosition += 6;
          } else {
            doc.setTextColor(150, 150, 150);
            doc.text('No risk assessment available', margin + 15, yPosition);
            doc.setTextColor(0, 0, 0);
            yPosition += 6;
          }

          yPosition += 8;
        });
        break;
    }

    // Footer
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text('This report contains confidential patient information', pageWidth / 2, 285, { align: 'center' });
      doc.text(`CliniTrack Medical Records System - Page ${i} of ${totalPages}`, pageWidth / 2, 292, { align: 'center' });
    }

    return doc;
  };

  const handleDownloadPDF = (reportId: string) => {
    const pdf = generatePDF(reportId);
    const reportTitle = reportTemplates.find(r => r.id === reportId)?.title || 'Report';
    const filename = `${reportTitle.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`;

    pdf.save(filename);
  };

  const handlePrintPDF = (reportId: string) => {
    const pdf = generatePDF(reportId);

    // Create blob URL for printing
    const blob = pdf.output('blob');
    const url = URL.createObjectURL(blob);

    // Open in new window for printing
    const printWindow = window.open(url, '_blank');
    if (printWindow) {
      printWindow.onload = () => {
        printWindow.print();
      };
    }

    // Clean up URL after a delay
    setTimeout(() => {
      URL.revokeObjectURL(url);
    }, 1000);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1>Medical Reports</h1>
          <p className="text-muted-foreground">
            Generate and print AI risk assessment reports
          </p>
        </div>
        <Badge variant="secondary" className="flex items-center gap-2">
          <FileBarChart className="h-4 w-4" />
          {filteredReports.length} Available
        </Badge>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Report Options</CardTitle>
          <CardDescription>Search reports and type patient name for individual assessments</CardDescription>
        </CardHeader>
        <CardContent>


          {/* new Search Patient */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {user?.role === 'doctor' && (
              <div className="relative">
                <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />

                <Input
                  placeholder="Search Patient..."
                  value={selectedPatientName}
                  onChange={(e) => setSelectedPatientName(e.target.value)}
                  onFocus={() => {
                    if (filteredPatients.length > 0) setShowDropdown(true);
                  }}
                  className="pl-10"
                />

                {/* new DROPDOWN RESULTS */}
                {showDropdown && (
                  <div className="dropdown-fixed  mt-1 w-full border rounded-lg shadow-lg max-h-60 overflow-y-auto" >

                    {filteredPatients.length > 0 ? (
                      filteredPatients.map((p) => (
                        <div
                          key={p.id}
                          onClick={() => {
                            setJustSelected(true);
                            setSelectedPatientName(p.name);
                            setSelectedPatientId(p.id);
                            setShowDropdown(false);
                          }}
                          className="px-3 py-2 hover:bg-yellow-500 cursor-pointer"
                        >
                          {p.name}
                        </div>
                      ))
                    ) : (
                      <div className="px-3 py-2 text-gray-500 italic">
                        No matching patients found
                      </div>
                    )}

                  </div>
                )}

              </div>
            )}
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {filteredReports.map((report) => {
          const IconComponent = report.icon;

          // Find patient by typed name (case-insensitive)
          const selectedPatient = patients.find((p) =>
            p.name.toLowerCase().includes(selectedPatientName.toLowerCase())
          );

          return (
            <Card key={report.id}>
              <CardHeader>
                <div className="flex items-center space-x-3">
                  <div className="p-2 bg-primary/10 rounded-lg">
                    <IconComponent className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <CardTitle className="text-base">{report.title}</CardTitle>
                    <CardDescription className="text-sm">
                      {report.description}
                    </CardDescription>
                  </div>
                </div>
              </CardHeader>

              <CardContent>
                <div className="space-y-4">
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Records:</span>
                    <span className="font-medium">{report.count}</span>
                  </div>

                  {report.requiresPatientSelection && (
                    <div className="text-xs text-muted-foreground">
                      {selectedPatientName
                        ? `Selected: ${selectedPatient ? selectedPatient.name : 'No matching patient'}`
                        : 'Please type a patient name above'}
                    </div>
                  )}

                  <Separator />

                  <div className="flex space-x-2">
                    <Button
                      size="sm"
                      onClick={() => handleDownloadPDF(report.id)}
                      className="flex-1"
                      disabled={report.requiresPatientSelection && !selectedPatient}
                    >
                      <Download className="mr-2 h-3 w-3" />
                      PDF
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => handlePrintPDF(report.id)}
                      className="flex-1"
                      disabled={report.requiresPatientSelection && !selectedPatient}
                    >
                      <Printer className="mr-2 h-3 w-3" />
                      Print
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Important Notice</CardTitle>
          <CardDescription>Medical data privacy and security</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-2 text-sm text-muted-foreground">
            <p>• Reports contain confidential patient information</p>
            <p>• Handle according to medical privacy guidelines</p>
            <p>• Store downloaded files securely</p>
            <p>• All report activities are logged for audit purposes</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}